name: Percy
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Percy Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
      - uses: actions/checkout@v1
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - run: npx percy snapshot _site
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
